namespace SubiektMobile.Infrastructure.Persistence.Entities;

public sealed class TwTowar
{
    public int Id { get; set; }
    public bool? Zablokowany { get; set; }
    public int? Rodzaj { get; set; }
    public string? Symbol { get; set; }
    public string? Nazwa { get; set; }
    public string? Opis { get; set; }
    public int? IdVatSp { get; set; }
    public int? IdVatZak { get; set; }
    public bool? JakPrzySp { get; set; }
    public string? JednMiary { get; set; }
    public string? Pkwiu { get; set; }
    public string? Sww { get; set; }
    public int? IdRabat { get; set; }
    public int? IdOpakowanie { get; set; }
    public bool? PrzezWartosc { get; set; }
    public int? IdPodstDostawca { get; set; }
    public string? DostSymbol { get; set; }
    public int? CzasDostawy { get; set; }
    public string? UrzNazwa { get; set; }
    public int? Plu { get; set; }
    public string? PodstKodKresk { get; set; }
    public int? IdTypKodu { get; set; }
    public bool? CenaOtwarta { get; set; }
    public bool? WagaEtykiet { get; set; }
    public bool? KontrolaTW { get; set; }
    public decimal? StanMin { get; set; }
    public string? JednStanMin { get; set; }
    public int? DniWaznosc { get; set; }
    public int? IdGrupa { get; set; }
    public string? Www { get; set; }
    public bool? SklepInternet { get; set; }
    public string? Pole1 { get; set; }
    public string? Pole2 { get; set; }
    public string? Pole3 { get; set; }
    public string? Pole4 { get; set; }
    public string? Pole5 { get; set; }
    public string? Pole6 { get; set; }
    public string? Pole7 { get; set; }
    public string? Pole8 { get; set; }
    public string? Uwagi { get; set; }
    public byte[]? Logo { get; set; }
    public bool? Usuniety { get; set; }
    public decimal? Objetosc { get; set; }
    public decimal? Masa { get; set; }
    public string? Charakter { get; set; }
    public string? JednMiaryZak { get; set; }
    public bool? JmZakInna { get; set; }
    public string? KodTowaru { get; set; }
    public int? IdKrajuPochodzenia { get; set; }
    public int? IdUjm { get; set; }
    public string? JednMiarySprz { get; set; }
    public bool? JmSprzInna { get; set; }
    public bool? SerwisAukcyjny { get; set; }
    public int? IdProducenta { get; set; }
    public bool? SprzedazMobilna { get; set; }
    public bool? IsFundPromocji { get; set; }
    public int? IdFundPromocji { get; set; }
    public int? DomyslnaKategoria { get; set; }
    public decimal? Wysokosc { get; set; }
    public decimal? Szerokosc { get; set; }
    public decimal? Glebokosc { get; set; }
    public decimal? StanMaks { get; set; }
    public bool? Akcyza { get; set; }
    public bool? AkcyzaZaznacz { get; set; }
    public decimal? AkcyzaKwota { get; set; }
    public bool? ObrotMarza { get; set; }
    public bool? OdwrotneObciazenie { get; set; }
    public int? ProgKwotowyOO { get; set; }
    public bool? DodawalnyDoZW { get; set; }
    public string? Isbn { get; set; }
    public string? Bloz7 { get; set; }
    public string? Bloz12 { get; set; }
    public string? KodUProducenta { get; set; }
    public string? Komunikat { get; set; }
    public DateTime? KomunikatOd { get; set; }
    public int? KomunikatDokumenty { get; set; }
    public bool? MechanizmPodzielonejPlatnosci { get; set; }
    public int? GrupaJpkVat { get; set; }
    public bool? OplCukrowaPodlega { get; set; }
    public decimal? OplCukrowaObj { get; set; }
    public decimal? OplCukrowaZawartoscCukru { get; set; }
    public bool? OplCukrowaInneSlodzace { get; set; }
    public bool? OplCukrowaSok { get; set; }
    public decimal? OplCukrowaKwota { get; set; }
    public bool? OplCukrowaKofeinaPodlega { get; set; }
    public decimal? OplCukrowaKofeinaKwota { get; set; }
    public bool? OplCukrowaNapojWeglElektr { get; set; }
    public decimal? OplCukrowaKwotaPowyzej { get; set; }
    public decimal? MasaNetto { get; set; }
    public int? IdKoduWyrobuAkcyzowego { get; set; }
    public string? AkcyzaMarkaWyrobow { get; set; }
    public string? AkcyzaWielkoscProducenta { get; set; }
    public int? ZnakiAkcyzy { get; set; }
    public DateTime? DataZmianyVatSprzedazy { get; set; }
    public bool? WegielPodlegaOswiadczeniu { get; set; }
    public string? WegielOpisPochodzenia { get; set; }
    public bool? PodlegaOplacieNaFunduszOchronyRolnictwa { get; set; }
    public bool? ObjetySysKaucyjnym { get; set; }
    public int? SKRodzajOpakowania { get; set; }
    public bool? SKOpakowanieZwracane { get; set; }
    public int? SKIdOpakowania { get; set; }
}
