import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FormEvent, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { apiClient } from '../../../api/client'
import { getCsrfHeader } from '../../../api/csrf'
import { ApiRequestError } from '../../../api/apiError'
import { useI18n } from '../../../app/i18n/i18nContext'
import { getProducts, type ProductListItem } from '../../products/api/productsApi'
import { getCustomerSites } from '../api/customersApi'

const client = apiClient as any
type Part = { id: string; customerPartNumber: string; productId: number; engineeringChange?: string | null }
type Code = { id: string; code: string; packagingTypeName: string }
type PackagingType = { id: string; code: string; name: string }

export function CustomerPackagingPage() {
  const { customerId = '' } = useParams()
  const { t } = useI18n()
  const qc = useQueryClient()
  const [siteId, setSiteId] = useState('')
  const [productSearch, setProductSearch] = useState('')
  const [selectedProduct, setSelectedProduct] = useState<ProductListItem | null>(null)
  const [error, setError] = useState<string | null>(null)
  const sites = useQuery({ queryKey: ['customer-sites', customerId], queryFn: () => getCustomerSites(customerId, '', 1, 100), enabled: Boolean(customerId) })
  const products = useQuery({ queryKey: ['customer-part-products', productSearch], queryFn: () => getProducts({ search: productSearch.trim(), page: 1, pageSize: 10 }), enabled: productSearch.trim().length >= 2 })
  const parts = useQuery<{ items: Part[] }>({ queryKey: ['customer-parts', customerId, siteId], queryFn: () => request(`/api/customers/${customerId}/packaging/parts`, { query: { siteId: siteId || undefined, page: 1, pageSize: 100 } }), enabled: Boolean(customerId) })
  const codes = useQuery<{ items: Code[] }>({ queryKey: ['customer-packaging-codes', customerId, siteId], queryFn: () => request(`/api/customers/${customerId}/packaging/codes`, { query: { siteId: siteId || undefined, page: 1, pageSize: 100 } }), enabled: Boolean(customerId) })
  const types = useQuery<{ items: PackagingType[] }>({ queryKey: ['packaging-types', 'active'], queryFn: () => request('/api/packaging-types', { query: { isActive: true, page: 1, pageSize: 100 } }) })
  const addPart = useMutation({ mutationFn: async (form: HTMLFormElement) => { if (!selectedProduct) throw new Error('product-required'); const d = new FormData(form); await request(`/api/customers/${customerId}/packaging/parts`, { headers: await getCsrfHeader(), body: { siteId: siteId || null, partNumber: String(d.get('partNumber')), productId: selectedProduct.id, defaultPackagingTypeId: null, engineeringChange: String(d.get('engineeringChange') || '') || null, isActive: true }, method: 'POST' }) }, onSuccess: () => { setSelectedProduct(null); setProductSearch(''); setError(null); void qc.invalidateQueries({ queryKey: ['customer-parts', customerId, siteId] }) }, onError: reason => setError(reason instanceof ApiRequestError ? reason.message : selectedProduct ? t('customers.packagingError') : t('customers.selectProductError')) })
  const addCode = useMutation({ mutationFn: async (form: HTMLFormElement) => { const d = new FormData(form); await request(`/api/customers/${customerId}/packaging/codes`, { headers: await getCsrfHeader(), body: { siteId: siteId || null, packagingTypeId: String(d.get('packagingTypeId')), code: String(d.get('code')), isActive: true }, method: 'POST' }) }, onSuccess: () => void qc.invalidateQueries({ queryKey: ['customer-packaging-codes', customerId, siteId] }), onError: reason => setError(reason instanceof ApiRequestError ? reason.message : t('customers.packagingError')) })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); addPart.mutate(event.currentTarget) }
  return <section className="mx-auto max-w-5xl"><Link className="mb-4 inline-block font-semibold text-blue-950 hover:underline" to={`/customers/${customerId}`}>← {t('customers.back')}</Link><h2 className="text-2xl font-bold">{t('customers.partsAndPackaging')}</h2><label className="mt-4 block max-w-md"><span className="font-semibold">{t('customers.mappingContext')}</span><select className="mt-2 h-12 w-full rounded border border-slate-300 px-3" onChange={e => setSiteId(e.target.value)} value={siteId}><option value="">{t('customers.customerContext')}</option>{sites.data?.items.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></label><form className="mt-5 grid gap-3 rounded-xl border border-slate-300 bg-white p-5 sm:grid-cols-3" onSubmit={submit}><input className="h-12 rounded border border-slate-300 px-3" name="partNumber" placeholder={t('customers.partNumber')} required /><ProductPicker selected={selectedProduct} search={productSearch} products={products.data?.items ?? []} loading={products.isFetching} onSearch={setProductSearch} onSelect={setSelectedProduct} onClear={() => { setSelectedProduct(null); setProductSearch('') }} t={t} /><input className="h-12 rounded border border-slate-300 px-3" name="engineeringChange" placeholder={t('customers.engineeringChange')} /><button className="min-h-12 rounded bg-blue-950 px-4 font-semibold text-white sm:col-span-3" type="submit">{t('customers.addPartMapping')}</button></form>{error && <p className="mt-4 text-red-800" role="alert">{error}</p>}<div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-slate-300 bg-white p-5"><h3 className="font-semibold">{t('customers.partMappings')}</h3><ul className="mt-3 divide-y">{parts.data?.items.map(x => <li className="py-3" key={x.id}><b>{x.customerPartNumber}</b> · {t('customers.productId')}: {x.productId}{x.engineeringChange && ` · E: ${x.engineeringChange}`}</li>)}</ul></section><section className="rounded-xl border border-slate-300 bg-white p-5"><h3 className="font-semibold">{t('customers.packagingCodes')}</h3><form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); addCode.mutate(e.currentTarget); e.currentTarget.reset() }}><select className="min-w-0 flex-1 rounded border border-slate-300 p-2" name="packagingTypeId" required><option value="">{t('customers.packaging')}</option>{types.data?.items.map(x => <option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select><input className="w-28 rounded border border-slate-300 p-2" name="code" placeholder="B" required /><button className="admin-action-button" type="submit">{t('packaging.add')}</button></form><ul className="mt-3 divide-y">{codes.data?.items.map(x => <li className="py-3" key={x.id}><b>{x.code}</b> · {x.packagingTypeName}</li>)}</ul></section></div></section>
}

function ProductPicker({ selected, search, products, loading, onSearch, onSelect, onClear, t }: { selected: ProductListItem | null; search: string; products: ProductListItem[]; loading: boolean; onSearch: (value: string) => void; onSelect: (product: ProductListItem) => void; onClear: () => void; t: (key: any) => string }) {
  return <div className="relative"><label className="sr-only" htmlFor="customer-part-product">{t('customers.selectProduct')}</label><input className="h-12 w-full rounded border border-slate-300 px-3" disabled={selected !== null} id="customer-part-product" onChange={e => onSearch(e.target.value)} placeholder={selected ? `${selected.symbol ?? selected.id} · ${selected.name ?? ''}` : t('customers.searchProduct')} value={selected ? `${selected.symbol ?? selected.id} · ${selected.name ?? ''}` : search} />{selected ? <button className="mt-1 text-sm font-semibold text-blue-950 underline" onClick={onClear} type="button">{t('customers.changeProduct')}</button> : search.trim().length >= 2 && <div className="absolute z-10 mt-1 max-h-56 w-full overflow-auto rounded border border-slate-300 bg-white shadow"><p className="px-3 py-2 text-sm text-slate-500">{loading ? t('customers.searchingProducts') : t('customers.selectProduct')}</p>{products.map(product => <button className="block w-full border-t border-slate-100 px-3 py-2 text-left hover:bg-slate-50" key={product.id} onClick={() => onSelect(product)} type="button"><b>{product.symbol ?? product.id}</b><span className="ml-2 text-sm text-slate-600">{product.name ?? t('products.unnamed')}</span></button>)}</div>}</div>
}

async function request(path: string, options: any): Promise<any> { const { data, error, response } = options.method === 'POST' ? await client.POST(path, options) : await client.GET(path, options); if (!response.ok || !data) throw new ApiRequestError(response.status, problemDetail(error)); return data }
function problemDetail(error: unknown): string | undefined { return typeof error === 'object' && error !== null && 'detail' in error && typeof error.detail === 'string' ? error.detail : undefined }
