import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useI18n } from '../../../app/i18n/i18nContext'
import { AppIcon } from '../../../shared/components/AppIcon'
import { formatDateTime } from '../../picking/pickingFormat'
import { getPalletDetails, issuePalletLabel, type PalletDetails, type PalletDetailsItem, type PalletLabelIssueMode, type PalletLabelLanguage } from '../api/palletsApi'
import { formatPalletQuantity, formatWeightKg, palletLocale, palletStatusClass, palletStatusKey } from '../palletFormat'

export function PalletDetailsPage() {
  const { language, t } = useI18n()
  const locale = palletLocale(language)
  const { palletId = '' } = useParams()
  const client = useQueryClient()
  const [labelLanguage, setLabelLanguage] = useState<PalletLabelLanguage>(0)
  const [issueError, setIssueError] = useState<string | null>(null)
  const details = useQuery({ queryKey: ['pallets', 'details', palletId], queryFn: () => getPalletDetails(palletId), enabled: Boolean(palletId), refetchOnMount: 'always' })
  const issue = useMutation({
    mutationFn: (mode: PalletLabelIssueMode) => issuePalletLabel(palletId, mode, labelLanguage),
    onMutate: () => setIssueError(null),
    onSuccess: (file, mode) => {
      const url = URL.createObjectURL(file)
      if (mode === 0) window.open(url, '_blank', 'noopener,noreferrer')
      else {
        const link = document.createElement('a')
        link.href = url
        link.download = `etykieta-${palletId}.pdf`
        link.click()
      }
      window.setTimeout(() => URL.revokeObjectURL(url), 60_000)
      void client.invalidateQueries({ queryKey: ['pallets', 'details', palletId] })
    },
    onError: () => setIssueError(t('pallets.details.issueError')),
  })

  if (details.isLoading) return <PageState text={t('pallets.details.loading')} />
  if (details.isError || !details.data) return <PageState error retry={() => void details.refetch()} text={t('pallets.details.error')} />
  const pallet = details.data

  return <section className="mx-auto max-w-[1400px]" aria-labelledby="pallet-details-heading">
    <Link aria-label={t('pallets.details.back')} className="admin-action-button mb-5" to={`/picking/${pallet.warehouseOrderId}`}><AppIcon className="size-5" name="arrowBack" />{t('pallets.details.back')}</Link>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_430px]">
      <div className="space-y-5">
        <header><p className="text-sm font-semibold text-slate-500">{t('pallets.details.eyebrow')}</p><h2 className="text-2xl font-bold tracking-tight text-blue-950 sm:text-4xl" id="pallet-details-heading">{t('pallets.details.title')}</h2></header>
        <section className="rounded-xl border border-slate-300 bg-white p-5 shadow-sm">
          <div className="grid gap-4 sm:grid-cols-[1fr_auto]"><div><span className={`inline-flex rounded-full px-3 py-1.5 text-sm font-bold ${palletStatusClass(pallet.status)}`}>{t(palletStatusKey(pallet.status))}</span><h3 className="mt-3 text-3xl font-bold text-blue-950">{pallet.palletNumber}</h3><p className="mt-1 text-lg text-slate-700">{t('pallets.details.order')}: <strong>{pallet.warehouseOrderNumber}</strong></p></div><div className="text-sm sm:text-right"><span className="block text-slate-500">{t('pallets.details.created')}</span><strong className="mt-1 block text-slate-900">{formatDateTime(pallet.closedAtUtc, locale)}</strong><span className="mt-1 block text-slate-600">{pallet.closedByName}</span></div></div>
        </section>
        <section className="rounded-xl border border-slate-300 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-lg font-bold text-blue-950"><AppIcon className="size-5" name="truck" />{t('pallets.details.customerData')}</h3><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">{t('pallets.details.customer')}</dt><dd className="mt-1 text-lg font-bold">{pallet.customerName}</dd></div><div><dt className="text-sm text-slate-500">{t('pallets.details.orderNumber')}</dt><dd className="mt-1 text-lg font-bold">{pallet.warehouseOrderNumber}</dd></div></dl></section>
        <section className="overflow-hidden rounded-xl border border-slate-300 bg-white shadow-sm"><header className="flex items-center justify-between gap-3 border-b border-slate-300 bg-slate-100 p-4"><h3 className="flex items-center gap-2 font-bold text-blue-950"><AppIcon className="size-5" name="list" />{t('pallets.details.content')}</h3><span className="rounded-full bg-slate-200 px-3 py-1 text-sm font-semibold">{t('pallets.details.itemsCount').replace('{count}', String(pallet.items.length))}</span></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="bg-white text-sm text-slate-500"><tr><th className="p-4 font-semibold">{t('orders.product')}</th><th className="p-4 text-right font-semibold">{t('orders.quantity')}</th><th className="p-4 text-right font-semibold">{t('pallets.details.unitWeight')}</th><th className="p-4 text-right font-semibold">{t('pallets.details.lineWeight')}</th></tr></thead><tbody className="divide-y divide-slate-200">{pallet.items.map((item) => <PalletItemRow item={item} key={item.warehouseOrderItemId} locale={locale} />)}</tbody></table></div></section>
        <section className="grid gap-3 sm:grid-cols-3"><WeightCard icon="scale" label={t('pallets.details.goodsWeight')} value={formatWeightKg(Number(pallet.goodsWeightKg), locale)} /><WeightCard icon="pallet" label={t('pallets.details.emptyPalletWeight')} value={formatWeightKg(Number(pallet.emptyPalletWeightKg), locale)} /><WeightCard icon="check" label={t('pallets.details.totalWeight')} value={formatWeightKg(Number(pallet.totalWeightKg), locale)} strong /></section>
        {issueError && <p className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm font-semibold text-red-900" role="alert">{issueError}</p>}
        <div className="grid gap-3 sm:grid-cols-2"><button className="flex min-h-12 items-center justify-center gap-2 rounded-lg bg-blue-950 px-4 font-semibold text-white hover:bg-blue-900 disabled:cursor-wait disabled:opacity-60" disabled={issue.isPending} onClick={() => issue.mutate(0)} type="button"><AppIcon className="size-5" name="print" />{issue.isPending ? t('pallets.details.issuing') : t('pallets.details.print')}</button><button className="flex min-h-12 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 font-semibold text-slate-800 hover:bg-slate-100 disabled:cursor-wait disabled:opacity-60" disabled={issue.isPending} onClick={() => issue.mutate(1)} type="button"><AppIcon className="size-5" name="download" />{t('pallets.details.download')}</button></div>
        <LabelIssues pallet={pallet} locale={locale} />
      </div>
      <aside className="h-fit xl:sticky xl:top-24"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 font-bold text-blue-950"><AppIcon className="size-5" name="info" />{t('pallets.details.labelPreview')}</h3><span className="text-sm text-slate-600">{t('pallets.details.labelFormat')}</span></div><label className="mb-3 flex items-center justify-between gap-3 rounded-lg border border-slate-300 bg-white p-3 text-sm font-semibold"><span>{t('pallets.details.labelLanguage')}</span><select className="rounded border border-slate-300 bg-white px-2 py-1" onChange={(event) => setLabelLanguage(Number(event.target.value) as PalletLabelLanguage)} value={labelLanguage}><option value={0}>{t('pallets.details.languagePolish')}</option><option value={1}>{t('pallets.details.languageEnglish')}</option></select></label><LabelPreview language={labelLanguage} pallet={pallet} locale={locale} /></aside>
    </div>
  </section>
}

function PalletItemRow({ item, locale }: { item: PalletDetailsItem; locale: string }) { return <tr><td className="p-4"><strong className="block text-blue-950">{item.productName}</strong><small className="text-slate-500">{item.productSymbol || `ID: ${item.productId}`}</small></td><td className="p-4 text-right font-semibold">{formatPalletQuantity(Number(item.quantity), locale)} {item.unit}</td><td className="p-4 text-right">{formatWeightKg(Number(item.unitWeightKg), locale)}</td><td className="p-4 text-right font-semibold">{formatWeightKg(Number(item.lineWeightKg), locale)}</td></tr> }
function WeightCard({ icon, label, value, strong }: { icon: 'scale' | 'pallet' | 'check'; label: string; value: string; strong?: boolean }) { return <div className={`rounded-xl border p-4 ${strong ? 'border-blue-300 bg-blue-50' : 'border-slate-300 bg-white'}`}><div className="flex items-center gap-2 text-sm font-semibold text-slate-600"><AppIcon className="size-5" name={icon} />{label}</div><p className={`mt-2 ${strong ? 'text-2xl text-blue-950' : 'text-xl'} font-bold`}>{value}</p></div> }
function LabelIssues({ pallet, locale }: { pallet: PalletDetails; locale: string }) { const { t } = useI18n(); return <section className="rounded-xl border border-slate-300 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-lg font-bold text-blue-950"><AppIcon className="size-5" name="list" />{t('pallets.details.issueHistory')}</h3>{pallet.labelIssues.length === 0 ? <p className="mt-3 text-sm text-slate-600">{t('pallets.details.issueHistoryEmpty')}</p> : <ol className="mt-4 space-y-3">{pallet.labelIssues.map((entry) => <li className="flex items-start justify-between gap-4 border-b border-slate-200 pb-3 last:border-0 last:pb-0" key={`${entry.number}-${entry.occurredAtUtc}`}><div><p className="font-semibold text-slate-900">{entry.number === 1 ? t('pallets.details.firstIssue') : t('pallets.details.reissue')} · {entry.mode === 0 ? t('pallets.details.issuePrint') : t('pallets.details.issueDownload')}</p><p className="mt-1 text-sm text-slate-600">{entry.actorDisplayName}</p></div><time className="shrink-0 text-right text-sm text-slate-600">{formatDateTime(entry.occurredAtUtc, locale)}</time></li>)}</ol>}</section> }
function LabelPreview({ pallet, locale, language }: { pallet: PalletDetails; locale: string; language: PalletLabelLanguage }) { const english = language === 1; const text = english ? { customer: 'CUSTOMER', order: 'Order', pallet: 'Pallet', content: 'CONTENT', goods: 'Goods weight', tare: 'Tare', total: 'Total weight' } : { customer: 'ZAMAWIAJĄCY', order: 'Zamówienie', pallet: 'Paleta', content: 'ZAWARTOŚĆ', goods: 'Masa towarów', tare: 'Tara', total: 'Masa całkowita' }; return <section className="rounded-xl border border-slate-300 bg-white p-6 text-black shadow-lg"><div className="border-b-2 border-black pb-4"><p className="text-xs font-bold uppercase tracking-wider">{text.customer}</p><p className="mt-2 text-xl font-black">{pallet.customerName}</p><p className="mt-3 text-sm font-bold">{text.order}: {pallet.warehouseOrderNumber}</p></div><div className="border-b-2 border-black py-6 text-center"><p className="text-xs font-bold uppercase tracking-wider">{text.pallet}</p><Code39Barcode value={pallet.palletNumber} /><p className="mt-3 text-xl font-black tracking-[0.16em]">{pallet.palletNumber}</p></div><div className="pt-4"><p className="mb-2 text-xs font-bold uppercase tracking-wider">{text.content}</p><ul className="space-y-2 text-sm">{pallet.items.map((item) => <li className="flex justify-between gap-3" key={item.warehouseOrderItemId}><span>{item.productName}</span><strong>{formatPalletQuantity(Number(item.quantity), locale)} {item.unit}</strong></li>)}</ul></div><div className="mt-6 grid grid-cols-3 gap-3 border-t-2 border-black pt-4 text-sm"><div><p className="font-bold">{text.goods}</p><p>{formatWeightKg(Number(pallet.goodsWeightKg), locale)}</p></div><div><p className="font-bold">{text.tare}</p><p>{formatWeightKg(Number(pallet.emptyPalletWeightKg), locale)}</p></div><div className="text-right"><p className="font-bold">{text.total}</p><p>{formatWeightKg(Number(pallet.totalWeightKg), locale)}</p></div></div></section> }

const code39Patterns: Record<string, string> = { '0': 'nnnwwnwnn', '1': 'wnnwnnnnw', '2': 'nnwwnnnnw', '3': 'wnwwnnnnn', '4': 'nnnwwnnnw', '5': 'wnnwwnnnn', '6': 'nnwwwnnnn', '7': 'nnnwnnwnw', '8': 'wnnwnnwnn', '9': 'nnwwnnwnn', A: 'wnnnnwnnw', B: 'nnwnnwnnw', C: 'wnwnnwnnn', D: 'nnnnwwnnw', E: 'wnnnwwnnn', F: 'nnwnwwnnn', L: 'nnwnnnnww', P: 'nnwnwnnwn', '-': 'nwnnnnwnw', '*': 'nwnnwnwnn' }
function Code39Barcode({ value }: { value: string }) { const bars = `*${value.toUpperCase()}*`.split('').flatMap((character, charIndex) => (code39Patterns[character] ?? code39Patterns['-']).split('').map((width, index) => ({ key: `${charIndex}-${index}`, bar: index % 2 === 0, width: width === 'w' ? 2 : 1 }))); return <div aria-label={value} className="mx-auto mt-3 flex h-16 max-w-full justify-center overflow-hidden bg-white px-2" role="img">{bars.map((bar) => <span aria-hidden="true" className={bar.bar ? 'bg-black' : 'bg-white'} key={bar.key} style={{ width: `${bar.width}px` }} />)}</div> }
function PageState({ text, error, retry }: { text: string; error?: boolean; retry?: () => void }) { const { t } = useI18n(); return <div role={error ? 'alert' : 'status'} className={`mx-auto grid min-h-64 max-w-3xl place-items-center rounded-xl border p-8 text-center ${error ? 'border-red-300 bg-red-50 text-red-900' : 'border-slate-300 bg-white text-slate-600'}`}><div><AppIcon className="mx-auto mb-3 size-8" name={error ? 'warning' : 'pallet'} /><p className="font-bold">{text}</p>{retry && <button className="mt-4 rounded-lg bg-blue-950 px-4 py-2 font-semibold text-white" onClick={retry} type="button">{t('picking.retry')}</button>}</div></div> }
