using MediatR;
using SubiektMobile.Application.Identity;
using SubiektMobile.Application.Products;
using SubiektMobile.Domain.Customers;

namespace SubiektMobile.Application.Customers;

public sealed record ListPackagingTypesQuery(string? Search, bool? IsActive, int Page, int PageSize) : IRequest<PagedResult<PackagingTypeDto>>;
public sealed record CreatePackagingTypeCommand(string Code, string Name, decimal TareWeightKg, decimal? DefaultCapacity, bool IsActive) : IRequest<PackagingTypeDto>;
public sealed record UpdatePackagingTypeCommand(Guid Id, string Code, string Name, decimal TareWeightKg, decimal? DefaultCapacity, long Version) : IRequest<PackagingTypeDto>;
public sealed record SetPackagingTypeActiveCommand(Guid Id, bool IsActive, long Version) : IRequest<PackagingTypeDto>;
public sealed record ListCustomerPackagingCodesQuery(Guid CustomerId, Guid? SiteId, int Page, int PageSize) : IRequest<PagedResult<CustomerPackagingCodeDto>>;
public sealed record CreateCustomerPackagingCodeCommand(Guid CustomerId, Guid? SiteId, Guid PackagingTypeId, string Code, bool IsActive) : IRequest<CustomerPackagingCodeDto>;
public sealed record UpdateCustomerPackagingCodeCommand(Guid CustomerId, Guid? SiteId, Guid Id, Guid PackagingTypeId, string Code, long Version) : IRequest<CustomerPackagingCodeDto>;
public sealed record SetCustomerPackagingCodeActiveCommand(Guid CustomerId, Guid? SiteId, Guid Id, bool IsActive, long Version) : IRequest<CustomerPackagingCodeDto>;
public sealed record ListCustomerPartMappingsQuery(Guid CustomerId, Guid? SiteId, string? Search, int Page, int PageSize) : IRequest<PagedResult<CustomerPartMappingDto>>;
public sealed record CreateCustomerPartMappingCommand(Guid CustomerId, Guid? SiteId, string PartNumber, int ProductId, Guid? DefaultPackagingTypeId, string? EngineeringChange, bool IsActive) : IRequest<CustomerPartMappingDto>;
public sealed record UpdateCustomerPartMappingCommand(Guid CustomerId, Guid? SiteId, Guid Id, string PartNumber, int ProductId, Guid? DefaultPackagingTypeId, string? EngineeringChange, long Version) : IRequest<CustomerPartMappingDto>;
public sealed record SetCustomerPartMappingActiveCommand(Guid CustomerId, Guid? SiteId, Guid Id, bool IsActive, long Version) : IRequest<CustomerPartMappingDto>;
public sealed record ResolveCustomerPartQuery(Guid CustomerId, Guid? SiteId, string PartNumber) : IRequest<CustomerPartResolutionDto>;

public sealed class PackagingHandlers(IPackagingStore store, ICustomerStore customers, IProductReadRepository products, IApplicationAuthorizationService authorization, IAuditEntryFactory audits, TimeProvider time) :
    IRequestHandler<ListPackagingTypesQuery, PagedResult<PackagingTypeDto>>, IRequestHandler<CreatePackagingTypeCommand, PackagingTypeDto>, IRequestHandler<UpdatePackagingTypeCommand, PackagingTypeDto>, IRequestHandler<SetPackagingTypeActiveCommand, PackagingTypeDto>,
    IRequestHandler<ListCustomerPackagingCodesQuery, PagedResult<CustomerPackagingCodeDto>>, IRequestHandler<CreateCustomerPackagingCodeCommand, CustomerPackagingCodeDto>, IRequestHandler<UpdateCustomerPackagingCodeCommand, CustomerPackagingCodeDto>, IRequestHandler<SetCustomerPackagingCodeActiveCommand, CustomerPackagingCodeDto>,
    IRequestHandler<ListCustomerPartMappingsQuery, PagedResult<CustomerPartMappingDto>>, IRequestHandler<CreateCustomerPartMappingCommand, CustomerPartMappingDto>, IRequestHandler<UpdateCustomerPartMappingCommand, CustomerPartMappingDto>, IRequestHandler<SetCustomerPartMappingActiveCommand, CustomerPartMappingDto>, IRequestHandler<ResolveCustomerPartQuery, CustomerPartResolutionDto>
{
    public Task<PagedResult<PackagingTypeDto>> Handle(ListPackagingTypesQuery r, CancellationToken ct) { authorization.Require(Permissions.CustomersManage); CustomerUseCases.ValidatePage(r.Page, r.PageSize); return store.ListPackagingTypesAsync(r.Search, r.IsActive, r.Page, r.PageSize, ct); }
    public async Task<PackagingTypeDto> Handle(CreatePackagingTypeCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); var now = time.GetUtcNow(); try { var x = PackagingType.Create(Guid.NewGuid(), r.Code, r.Name, r.TareWeightKg, r.DefaultCapacity, r.IsActive, now); Save(await store.AddPackagingTypeAsync(x, audits.Create(a, "PackagingTypeCreated", "PackagingType", x.Id, now), ct)); return Map(x); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } }
    public async Task<PackagingTypeDto> Handle(UpdatePackagingTypeCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); var x = await Type(r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); try { x.Update(r.Code, r.Name, r.TareWeightKg, r.DefaultCapacity, now); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } Save(await store.SavePackagingTypeAsync(x, r.Version, audits.Create(a, "PackagingTypeUpdated", "PackagingType", x.Id, now), ct)); return Map(x); }
    public async Task<PackagingTypeDto> Handle(SetPackagingTypeActiveCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); var x = await Type(r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); x.SetActive(r.IsActive, now); Save(await store.SavePackagingTypeAsync(x, r.Version, audits.Create(a, r.IsActive ? "PackagingTypeActivated" : "PackagingTypeDeactivated", "PackagingType", x.Id, now), ct)); return Map(x); }
    public async Task<PagedResult<CustomerPackagingCodeDto>> Handle(ListCustomerPackagingCodesQuery r, CancellationToken ct) { authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); CustomerUseCases.ValidatePage(r.Page, r.PageSize); return await store.ListPackagingCodesAsync(r.CustomerId, r.SiteId, r.Page, r.PageSize, ct); }
    public async Task<CustomerPackagingCodeDto> Handle(CreateCustomerPackagingCodeCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); await ActiveType(r.PackagingTypeId, ct); var now = time.GetUtcNow(); try { var x = CustomerPackagingCode.Create(Guid.NewGuid(), r.CustomerId, r.SiteId, r.PackagingTypeId, r.Code, r.IsActive, now); Save(await store.AddPackagingCodeAsync(x, audits.Create(a, "CustomerPackagingCodeCreated", "CustomerPackagingCode", x.Id, now), ct)); return (await store.ListPackagingCodesAsync(r.CustomerId, r.SiteId, 1, 100, ct)).Items.Single(y => y.Id == x.Id); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } }
    public async Task<CustomerPackagingCodeDto> Handle(UpdateCustomerPackagingCodeCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); await ActiveType(r.PackagingTypeId, ct); var x = await Code(r.CustomerId, r.SiteId, r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); try { x.Update(r.PackagingTypeId, r.Code, now); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } Save(await store.SavePackagingCodeAsync(x, r.Version, audits.Create(a, "CustomerPackagingCodeUpdated", "CustomerPackagingCode", x.Id, now), ct)); return (await store.ListPackagingCodesAsync(r.CustomerId, r.SiteId, 1, 100, ct)).Items.Single(y => y.Id == x.Id); }
    public async Task<CustomerPackagingCodeDto> Handle(SetCustomerPackagingCodeActiveCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); var x = await Code(r.CustomerId, r.SiteId, r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); x.SetActive(r.IsActive, now); Save(await store.SavePackagingCodeAsync(x, r.Version, audits.Create(a, r.IsActive ? "CustomerPackagingCodeActivated" : "CustomerPackagingCodeDeactivated", "CustomerPackagingCode", x.Id, now), ct)); return (await store.ListPackagingCodesAsync(r.CustomerId, r.SiteId, 1, 100, ct)).Items.Single(y => y.Id == x.Id); }
    public async Task<PagedResult<CustomerPartMappingDto>> Handle(ListCustomerPartMappingsQuery r, CancellationToken ct) { authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); CustomerUseCases.ValidatePage(r.Page, r.PageSize); return await store.ListPartMappingsAsync(r.CustomerId, r.SiteId, r.Search, r.Page, r.PageSize, ct); }
    public async Task<CustomerPartMappingDto> Handle(CreateCustomerPartMappingCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); await Product(r.ProductId, ct); if (r.DefaultPackagingTypeId is not null) await ActiveType(r.DefaultPackagingTypeId.Value, ct); var now = time.GetUtcNow(); try { var x = CustomerPartMapping.Create(Guid.NewGuid(), r.CustomerId, r.SiteId, r.PartNumber, r.ProductId, r.DefaultPackagingTypeId, r.EngineeringChange, r.IsActive, now); Save(await store.AddPartMappingAsync(x, audits.Create(a, "CustomerPartMappingCreated", "CustomerPartMapping", x.Id, now), ct)); return (await store.ListPartMappingsAsync(r.CustomerId, r.SiteId, null, 1, 100, ct)).Items.Single(y => y.Id == x.Id); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } }
    public async Task<CustomerPartMappingDto> Handle(UpdateCustomerPartMappingCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); await Product(r.ProductId, ct); if (r.DefaultPackagingTypeId is not null) await ActiveType(r.DefaultPackagingTypeId.Value, ct); var x = await Mapping(r.CustomerId, r.SiteId, r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); try { x.Update(r.PartNumber, r.ProductId, r.DefaultPackagingTypeId, r.EngineeringChange, now); } catch (ArgumentException e) { throw new RequestValidationException(e.Message); } Save(await store.SavePartMappingAsync(x, r.Version, audits.Create(a, "CustomerPartMappingUpdated", "CustomerPartMapping", x.Id, now), ct)); return (await store.ListPartMappingsAsync(r.CustomerId, r.SiteId, null, 1, 100, ct)).Items.Single(y => y.Id == x.Id); }
    public async Task<CustomerPartMappingDto> Handle(SetCustomerPartMappingActiveCommand r, CancellationToken ct) { var a = authorization.Require(Permissions.CustomersManage); var x = await Mapping(r.CustomerId, r.SiteId, r.Id, true, ct); Version(x.Version, r.Version); var now = time.GetUtcNow(); x.SetActive(r.IsActive, now); Save(await store.SavePartMappingAsync(x, r.Version, audits.Create(a, r.IsActive ? "CustomerPartMappingActivated" : "CustomerPartMappingDeactivated", "CustomerPartMapping", x.Id, now), ct)); return (await store.ListPartMappingsAsync(r.CustomerId, r.SiteId, null, 1, 100, ct)).Items.Single(y => y.Id == x.Id); }
    public async Task<CustomerPartResolutionDto> Handle(ResolveCustomerPartQuery r, CancellationToken ct) { authorization.Require(Permissions.CustomersManage); await Context(r.CustomerId, r.SiteId, ct); var result = await store.ResolveAsync(r.CustomerId, r.SiteId, r.PartNumber, ct); return result.Mapping is not null && await products.GetProductWarehouseOrderSnapshotAsync(result.Mapping.ProductId, ct) is null ? result with { Readiness = CustomerPartReadiness.ProductUnavailable } : result; }
    private async Task Context(Guid customer, Guid? site, CancellationToken ct) { _ = await CustomerUseCases.FindCustomer(customer, customers, false, ct); if (site is not null) _ = await CustomerUseCases.FindSite(customer, site.Value, customers, false, ct); }
    private async Task Product(int id, CancellationToken ct) { if (await products.GetProductWarehouseOrderSnapshotAsync(id, ct) is null) throw new RequestValidationException("The selected Subiekt product no longer exists."); }
    private async Task<PackagingType> Type(Guid id, bool tracking, CancellationToken ct) => await store.FindPackagingTypeAsync(id, tracking, ct) ?? throw new ResourceNotFoundException("Packaging type was not found.");
    private async Task ActiveType(Guid id, CancellationToken ct) { if (!(await Type(id, false, ct)).IsActive) throw new RequestValidationException("The selected packaging type is inactive."); }
    private async Task<CustomerPackagingCode> Code(Guid customer, Guid? site, Guid id, bool tracking, CancellationToken ct) => await store.FindPackagingCodeAsync(customer, site, id, tracking, ct) ?? throw new ResourceNotFoundException("Customer packaging code was not found.");
    private async Task<CustomerPartMapping> Mapping(Guid customer, Guid? site, Guid id, bool tracking, CancellationToken ct) => await store.FindPartMappingAsync(customer, site, id, tracking, ct) ?? throw new ResourceNotFoundException("Customer part mapping was not found.");
    private static void Version(long actual, long expected) { if (expected <= 0 || actual != expected) throw new ResourceConflictException("Configuration was modified by another request."); }
    private static void Save(PackagingStoreResult result) { if (result == PackagingStoreResult.Conflict) throw new ResourceConflictException("Configuration was modified by another request."); if (result == PackagingStoreResult.NotFound) throw new ResourceNotFoundException("Configuration was not found."); }
    private static PackagingTypeDto Map(PackagingType x) => new(x.Id, x.Code, x.Name, x.TareWeightKg, x.DefaultCapacity, x.IsActive, x.UpdatedAtUtc, x.Version);
}
