/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Diagnostics/db-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "application/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "text/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDetailsResponse"];
                        "application/json": components["schemas"]["ProductDetailsResponse"];
                        "text/json": components["schemas"]["ProductDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["FileContentResult"];
                        "image/png": components["schemas"]["FileContentResult"];
                        "image/gif": components["schemas"]["FileContentResult"];
                        "image/bmp": components["schemas"]["FileContentResult"];
                        "image/webp": components["schemas"]["FileContentResult"];
                        "application/octet-stream": components["schemas"]["FileContentResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["ProblemDetails"];
                        "image/png": components["schemas"]["ProblemDetails"];
                        "image/gif": components["schemas"]["ProblemDetails"];
                        "image/bmp": components["schemas"]["ProblemDetails"];
                        "image/webp": components["schemas"]["ProblemDetails"];
                        "application/octet-stream": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EntityTagHeaderValue: {
            tag?: components["schemas"]["StringSegment"];
            isWeak?: boolean;
        };
        FileContentResult: {
            /** Format: byte */
            fileContents?: string;
            contentType?: null | string;
            fileDownloadName?: null | string;
            /** Format: date-time */
            lastModified?: null | string;
            entityTag?: null | components["schemas"]["EntityTagHeaderValue"];
            enableRangeProcessing?: boolean;
        };
        PagedResponseOfProductListItemResponse: {
            items: components["schemas"]["ProductListItemResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProductDetailsResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            description: null | string;
            unit: null | string;
            primaryBarcode: null | string;
            additionalBarcodes: string[];
            vat: null | components["schemas"]["ProductVatDto"];
            imageUrl: null | string;
            warehouses: components["schemas"]["ProductStockDto"][];
            prices: components["schemas"]["ProductPriceDto"][];
        };
        ProductListItemResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            imageUrl: null | string;
            stock: null | components["schemas"]["ProductStockDto"];
            price: null | components["schemas"]["ProductListPriceDto"];
        };
        ProductListPriceDto: {
            /** Format: int32 */
            level: number | string;
            name: string;
            /** Format: double */
            gross: number | string;
            currency: null | string;
        };
        ProductPriceDto: {
            /** Format: int32 */
            level: number | string;
            name: string;
            /** Format: double */
            net: null | number | string;
            /** Format: double */
            gross: null | number | string;
            currency: null | string;
        };
        ProductStockDto: {
            /** Format: int32 */
            warehouseId: number | string;
            warehouseSymbol: null | string;
            warehouseName: null | string;
            isMain: boolean;
            /** Format: double */
            quantity: number | string;
            /** Format: double */
            reserved: number | string;
            /** Format: double */
            available: number | string;
            /** Format: double */
            minimum: null | number | string;
            /** Format: double */
            maximum: null | number | string;
            unit: null | string;
        };
        ProductVatDto: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            /** Format: double */
            rate: null | number | string;
        };
        StringSegment: {
            buffer?: null | string;
            /** Format: int32 */
            offset?: number | string;
            /** Format: int32 */
            length?: number | string;
            value?: null | string;
            hasValue?: boolean;
        };
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
