/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/administrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdministratorDto"][];
                        "application/json": components["schemas"]["AdministratorDto"][];
                        "text/json": components["schemas"]["AdministratorDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAdministratorRequest"];
                    "text/json": components["schemas"]["CreateAdministratorRequest"];
                    "application/*+json": components["schemas"]["CreateAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedAdministratorDto"];
                        "application/json": components["schemas"]["CreatedAdministratorDto"];
                        "text/json": components["schemas"]["CreatedAdministratorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAdministratorRequest"];
                    "text/json": components["schemas"]["UpdateAdministratorRequest"];
                    "application/*+json": components["schemas"]["UpdateAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdministratorDto"];
                        "application/json": components["schemas"]["AdministratorDto"];
                        "text/json": components["schemas"]["AdministratorDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetAdministratorPasswordRequest"];
                    "text/json": components["schemas"]["ResetAdministratorPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetAdministratorPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"][];
                        "application/json": components["schemas"]["OrganizationDto"][];
                        "text/json": components["schemas"]["OrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                    "text/json": components["schemas"]["CreateOrganizationRequest"];
                    "application/*+json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"];
                        "application/json": components["schemas"]["OrganizationDto"];
                        "text/json": components["schemas"]["OrganizationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationRequest"];
                    "text/json": components["schemas"]["UpdateOrganizationRequest"];
                    "application/*+json": components["schemas"]["UpdateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"];
                        "application/json": components["schemas"]["OrganizationDto"];
                        "text/json": components["schemas"]["OrganizationDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"][];
                        "application/json": components["schemas"]["EmployeeDto"][];
                        "text/json": components["schemas"]["EmployeeDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEmployeeRequest"];
                    "text/json": components["schemas"]["CreateEmployeeRequest"];
                    "application/*+json": components["schemas"]["CreateEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"];
                        "application/json": components["schemas"]["EmployeeDto"];
                        "text/json": components["schemas"]["EmployeeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    employeeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEmployeeRequest"];
                    "text/json": components["schemas"]["UpdateEmployeeRequest"];
                    "application/*+json": components["schemas"]["UpdateEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"];
                        "application/json": components["schemas"]["EmployeeDto"];
                        "text/json": components["schemas"]["EmployeeDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees/{employeeId}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    employeeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsrfTokenResponse"];
                        "application/json": components["schemas"]["CsrfTokenResponse"];
                        "text/json": components["schemas"]["CsrfTokenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/bootstrap-administrator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Setup-Token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BootstrapAdministratorRequest"];
                    "text/json": components["schemas"]["BootstrapAdministratorRequest"];
                    "application/*+json": components["schemas"]["BootstrapAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/administrator/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdministratorSignInRequest"];
                    "text/json": components["schemas"]["AdministratorSignInRequest"];
                    "application/*+json": components["schemas"]["AdministratorSignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/administrator/change-password": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never; };
        get?: never;
        put?: never;
        post: {
            parameters: { query?: never; header?: never; path?: never; cookie?: never; };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeOwnPasswordRequest"];
                    "text/json": components["schemas"]["ChangeOwnPasswordRequest"];
                    "application/*+json": components["schemas"]["ChangeOwnPasswordRequest"];
                };
            };
            responses: { 204: { headers: { [name: string]: unknown; }; content?: never; }; };
        };
        delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/api/auth/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicOrganizationDto"][];
                        "application/json": components["schemas"]["PublicOrganizationDto"][];
                        "text/json": components["schemas"]["PublicOrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/organizations/{organizationId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicEmployeeDto"][];
                        "application/json": components["schemas"]["PublicEmployeeDto"][];
                        "text/json": components["schemas"]["PublicEmployeeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/employee/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectEmployeeRequest"];
                    "text/json": components["schemas"]["SelectEmployeeRequest"];
                    "application/*+json": components["schemas"]["SelectEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentActor"];
                        "application/json": components["schemas"]["CurrentActor"];
                        "text/json": components["schemas"]["CurrentActor"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Diagnostics/db-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "application/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "text/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDetailsResponse"];
                        "application/json": components["schemas"]["ProductDetailsResponse"];
                        "text/json": components["schemas"]["ProductDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["FileContentResult"];
                        "image/png": components["schemas"]["FileContentResult"];
                        "image/gif": components["schemas"]["FileContentResult"];
                        "image/bmp": components["schemas"]["FileContentResult"];
                        "image/webp": components["schemas"]["FileContentResult"];
                        "application/octet-stream": components["schemas"]["FileContentResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["ProblemDetails"];
                        "image/png": components["schemas"]["ProblemDetails"];
                        "image/gif": components["schemas"]["ProblemDetails"];
                        "image/bmp": components["schemas"]["ProblemDetails"];
                        "image/webp": components["schemas"]["ProblemDetails"];
                        "application/octet-stream": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActorKind: number;
        AdministratorDto: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            isActive: boolean;
            isBootstrapAdministrator: boolean;
            requiresPasswordChange: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        AdministratorSignInRequest: {
            username: string;
            password: string;
        };
        BootstrapAdministratorRequest: {
            username: string;
            displayName: string;
            password: string;
        };
        ChangeOwnPasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CreateAdministratorRequest: {
            username: string;
            displayName: string;
        };
        CreatedAdministratorDto: {
            administrator: components["schemas"]["AdministratorDto"];
            temporaryPassword: string;
        };
        CreateEmployeeRequest: {
            code: string;
            displayName: string;
        };
        CreateOrganizationRequest: {
            code: string;
            name: string;
        };
        CsrfTokenResponse: {
            token: string;
            headerName: string;
        };
        CurrentActor: {
            kind: components["schemas"]["ActorKind"];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: null | string;
            displayName: string;
            permissions: string[];
            /** Format: uuid */
            sessionId: string;
            requiresPasswordChange: boolean;
        };
        CurrentSessionResponse: {
            /** Format: date-time */
            expiresAtUtc: string;
            actor: components["schemas"]["CurrentActor"];
        };
        EmployeeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            code: string;
            displayName: string;
            isActive: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        EntityTagHeaderValue: {
            tag?: components["schemas"]["StringSegment"];
            isWeak?: boolean;
        };
        FileContentResult: {
            /** Format: byte */
            fileContents?: string;
            contentType?: null | string;
            fileDownloadName?: null | string;
            /** Format: date-time */
            lastModified?: null | string;
            entityTag?: null | components["schemas"]["EntityTagHeaderValue"];
            enableRangeProcessing?: boolean;
        };
        OrganizationDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            isActive: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        PagedResponseOfProductListItemResponse: {
            items: components["schemas"]["ProductListItemResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProductDetailsResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            description: null | string;
            unit: null | string;
            primaryBarcode: null | string;
            additionalBarcodes: string[];
            vat: null | components["schemas"]["ProductVatDto"];
            imageUrl: null | string;
            warehouses: components["schemas"]["ProductStockDto"][];
            prices: components["schemas"]["ProductPriceDto"][];
        };
        ProductListItemResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            unit: null | string;
            imageUrl: null | string;
            stock: null | components["schemas"]["ProductStockDto"];
        };
        ProductPriceDto: {
            /** Format: int32 */
            level: number | string;
            name: string;
            /** Format: double */
            net: null | number | string;
            /** Format: double */
            gross: null | number | string;
            currency: null | string;
        };
        ProductStockDto: {
            /** Format: int32 */
            warehouseId: number | string;
            warehouseSymbol: null | string;
            warehouseName: null | string;
            isMain: boolean;
            /** Format: double */
            quantity: number | string;
            /** Format: double */
            reserved: number | string;
            /** Format: double */
            available: number | string;
            /** Format: double */
            minimum: null | number | string;
            /** Format: double */
            maximum: null | number | string;
            unit: null | string;
        };
        ProductVatDto: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            /** Format: double */
            rate: null | number | string;
        };
        PublicEmployeeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            code: string;
            displayName: string;
        };
        PublicOrganizationDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        ResetAdministratorPasswordRequest: {
            password: string;
        };
        SelectEmployeeRequest: {
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            employeeId: string;
        };
        SetActiveRequest: {
            isActive: boolean;
        };
        StringSegment: {
            buffer?: null | string;
            /** Format: int32 */
            offset?: number | string;
            /** Format: int32 */
            length?: number | string;
            value?: null | string;
            hasValue?: boolean;
        };
        UpdateAdministratorRequest: {
            username: string;
            displayName: string;
        };
        UpdateEmployeeRequest: {
            code: string;
            displayName: string;
        };
        UpdateOrganizationRequest: {
            code: string;
            name: string;
        };
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
