/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/administrators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdministratorDto"][];
                        "application/json": components["schemas"]["AdministratorDto"][];
                        "text/json": components["schemas"]["AdministratorDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAdministratorRequest"];
                    "text/json": components["schemas"]["CreateAdministratorRequest"];
                    "application/*+json": components["schemas"]["CreateAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreatedAdministratorDto"];
                        "application/json": components["schemas"]["CreatedAdministratorDto"];
                        "text/json": components["schemas"]["CreatedAdministratorDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAdministratorRequest"];
                    "text/json": components["schemas"]["UpdateAdministratorRequest"];
                    "application/*+json": components["schemas"]["UpdateAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AdministratorDto"];
                        "application/json": components["schemas"]["AdministratorDto"];
                        "text/json": components["schemas"]["AdministratorDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResetAdministratorPasswordRequest"];
                    "text/json": components["schemas"]["ResetAdministratorPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetAdministratorPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/administrators/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"][];
                        "application/json": components["schemas"]["OrganizationDto"][];
                        "text/json": components["schemas"]["OrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrganizationRequest"];
                    "text/json": components["schemas"]["CreateOrganizationRequest"];
                    "application/*+json": components["schemas"]["CreateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"];
                        "application/json": components["schemas"]["OrganizationDto"];
                        "text/json": components["schemas"]["OrganizationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrganizationRequest"];
                    "text/json": components["schemas"]["UpdateOrganizationRequest"];
                    "application/*+json": components["schemas"]["UpdateOrganizationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrganizationDto"];
                        "application/json": components["schemas"]["OrganizationDto"];
                        "text/json": components["schemas"]["OrganizationDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"][];
                        "application/json": components["schemas"]["EmployeeDto"][];
                        "text/json": components["schemas"]["EmployeeDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEmployeeRequest"];
                    "text/json": components["schemas"]["CreateEmployeeRequest"];
                    "application/*+json": components["schemas"]["CreateEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"];
                        "application/json": components["schemas"]["EmployeeDto"];
                        "text/json": components["schemas"]["EmployeeDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    employeeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEmployeeRequest"];
                    "text/json": components["schemas"]["UpdateEmployeeRequest"];
                    "application/*+json": components["schemas"]["UpdateEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDto"];
                        "application/json": components["schemas"]["EmployeeDto"];
                        "text/json": components["schemas"]["EmployeeDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/organizations/{organizationId}/employees/{employeeId}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                    employeeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetActiveRequest"];
                    "text/json": components["schemas"]["SetActiveRequest"];
                    "application/*+json": components["schemas"]["SetActiveRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsrfTokenResponse"];
                        "application/json": components["schemas"]["CsrfTokenResponse"];
                        "text/json": components["schemas"]["CsrfTokenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/bootstrap-administrator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Setup-Token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BootstrapAdministratorRequest"];
                    "text/json": components["schemas"]["BootstrapAdministratorRequest"];
                    "application/*+json": components["schemas"]["BootstrapAdministratorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/administrator/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdministratorSignInRequest"];
                    "text/json": components["schemas"]["AdministratorSignInRequest"];
                    "application/*+json": components["schemas"]["AdministratorSignInRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicOrganizationDto"][];
                        "application/json": components["schemas"]["PublicOrganizationDto"][];
                        "text/json": components["schemas"]["PublicOrganizationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/organizations/{organizationId}/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    organizationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicEmployeeDto"][];
                        "application/json": components["schemas"]["PublicEmployeeDto"][];
                        "text/json": components["schemas"]["PublicEmployeeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/employee/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SelectEmployeeRequest"];
                    "text/json": components["schemas"]["SelectEmployeeRequest"];
                    "application/*+json": components["schemas"]["SelectEmployeeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentSessionResponse"];
                        "application/json": components["schemas"]["CurrentSessionResponse"];
                        "text/json": components["schemas"]["CurrentSessionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentActor"];
                        "application/json": components["schemas"]["CurrentActor"];
                        "text/json": components["schemas"]["CurrentActor"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/administrator/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeOwnPasswordRequest"];
                    "text/json": components["schemas"]["ChangeOwnPasswordRequest"];
                    "application/*+json": components["schemas"]["ChangeOwnPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Diagnostics/db-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfOrderListItemDto"];
                        "application/json": components["schemas"]["PagedResultOfOrderListItemDto"];
                        "text/json": components["schemas"]["PagedResultOfOrderListItemDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                    "text/json": components["schemas"]["CreateOrderRequest"];
                    "application/*+json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateOrderRequest"];
                    "text/json": components["schemas"]["UpdateOrderRequest"];
                    "application/*+json": components["schemas"]["UpdateOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddOrderItemRequest"];
                    "text/json": components["schemas"]["AddOrderItemRequest"];
                    "application/*+json": components["schemas"]["AddOrderItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    version?: number | string;
                };
                header?: never;
                path: {
                    id: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VersionRequest"];
                    "text/json": components["schemas"]["VersionRequest"];
                    "application/*+json": components["schemas"]["VersionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/available-assignees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AvailableOrderAssigneeDto"][];
                        "application/json": components["schemas"]["AvailableOrderAssigneeDto"][];
                        "text/json": components["schemas"]["AvailableOrderAssigneeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/picking-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfigureOrderPickingRequest"];
                    "text/json": components["schemas"]["ConfigureOrderPickingRequest"];
                    "application/*+json": components["schemas"]["ConfigureOrderPickingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OrderDto"];
                        "application/json": components["schemas"]["OrderDto"];
                        "text/json": components["schemas"]["OrderDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfPalletListItemDto"];
                        "application/json": components["schemas"]["PagedResultOfPalletListItemDto"];
                        "text/json": components["schemas"]["PagedResultOfPalletListItemDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/pallets/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PalletCandidatesDto"];
                        "application/json": components["schemas"]["PalletCandidatesDto"];
                        "text/json": components["schemas"]["PalletCandidatesDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/pallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePalletRequest"];
                    "text/json": components["schemas"]["CreatePalletRequest"];
                    "application/*+json": components["schemas"]["CreatePalletRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PalletDetailsDto"];
                        "application/json": components["schemas"]["PalletDetailsDto"];
                        "text/json": components["schemas"]["PalletDetailsDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pallets/{palletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    palletId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PalletDetailsDto"];
                        "application/json": components["schemas"]["PalletDetailsDto"];
                        "text/json": components["schemas"]["PalletDetailsDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pallets/{palletId}/label-preview": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never; };
        get: {
            parameters: { query?: { language?: components["schemas"]["PalletLabelLanguage"]; }; header?: never; path: { palletId: string; }; cookie?: never; };
            requestBody?: never;
            responses: {
                200: { headers: { [name: string]: unknown; }; content: { "application/pdf": Blob; }; };
                404: { headers: { [name: string]: unknown; }; content: { "application/json": components["schemas"]["ProblemDetails"]; }; };
            };
        };
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/api/pallets/{palletId}/label-issues": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never; };
        get?: never;
        post: {
            parameters: { query?: never; header?: never; path: { palletId: string; }; cookie?: never; };
            requestBody: { content: { "application/json": components["schemas"]["PalletLabelIssueRequest"]; }; };
            responses: {
                200: { headers: { [name: string]: unknown; }; content: { "application/pdf": Blob; }; };
                400: { headers: { [name: string]: unknown; }; content: { "application/json": components["schemas"]["ProblemDetails"]; }; };
                404: { headers: { [name: string]: unknown; }; content: { "application/json": components["schemas"]["ProblemDetails"]; }; };
            };
        };
        put?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/api/picking/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                    search?: string;
                    status?: components["schemas"]["PickingOrderStatus"];
                    dueDateFrom?: string;
                    dueDateTo?: string;
                    customer?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfPickingOrderListItemDto"];
                        "application/json": components["schemas"]["PagedResultOfPickingOrderListItemDto"];
                        "text/json": components["schemas"]["PagedResultOfPickingOrderListItemDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickingOrderDetailsDto"];
                        "application/json": components["schemas"]["PickingOrderDetailsDto"];
                        "text/json": components["schemas"]["PickingOrderDetailsDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path: {
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfPickingHistoryItemDto"];
                        "application/json": components["schemas"]["PagedResultOfPickingHistoryItemDto"];
                        "text/json": components["schemas"]["PagedResultOfPickingHistoryItemDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}/items/{itemId}/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PickingMutationRequest"];
                    "text/json": components["schemas"]["PickingMutationRequest"];
                    "application/*+json": components["schemas"]["PickingMutationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickingOrderDetailsDto"];
                        "application/json": components["schemas"]["PickingOrderDetailsDto"];
                        "text/json": components["schemas"]["PickingOrderDetailsDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}/items/{itemId}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PickingMutationRequest"];
                    "text/json": components["schemas"]["PickingMutationRequest"];
                    "application/*+json": components["schemas"]["PickingMutationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickingOrderDetailsDto"];
                        "application/json": components["schemas"]["PickingOrderDetailsDto"];
                        "text/json": components["schemas"]["PickingOrderDetailsDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}/items/{itemId}/pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PackPickingItemRequest"];
                    "text/json": components["schemas"]["PackPickingItemRequest"];
                    "application/*+json": components["schemas"]["PackPickingItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickingOrderDetailsDto"];
                        "application/json": components["schemas"]["PickingOrderDetailsDto"];
                        "text/json": components["schemas"]["PickingOrderDetailsDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/picking/orders/{orderId}/items/{itemId}/undo-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: string;
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PickingMutationRequest"];
                    "text/json": components["schemas"]["PickingMutationRequest"];
                    "application/*+json": components["schemas"]["PickingMutationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickingOrderDetailsDto"];
                        "application/json": components["schemas"]["PickingOrderDetailsDto"];
                        "text/json": components["schemas"]["PickingOrderDetailsDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "application/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                        "text/json": components["schemas"]["PagedResponseOfProductListItemResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ValidationProblemDetails"];
                        "application/json": components["schemas"]["ValidationProblemDetails"];
                        "text/json": components["schemas"]["ValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProductDetailsResponse"];
                        "application/json": components["schemas"]["ProductDetailsResponse"];
                        "text/json": components["schemas"]["ProductDetailsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["FileContentResult"];
                        "image/png": components["schemas"]["FileContentResult"];
                        "image/gif": components["schemas"]["FileContentResult"];
                        "image/bmp": components["schemas"]["FileContentResult"];
                        "image/webp": components["schemas"]["FileContentResult"];
                        "application/octet-stream": components["schemas"]["FileContentResult"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": components["schemas"]["ProblemDetails"];
                        "image/png": components["schemas"]["ProblemDetails"];
                        "image/gif": components["schemas"]["ProblemDetails"];
                        "image/bmp": components["schemas"]["ProblemDetails"];
                        "image/webp": components["schemas"]["ProblemDetails"];
                        "application/octet-stream": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActorKind: number;
        AddOrderItemRequest: {
            /** Format: int32 */
            productId: number | string;
            /** Format: double */
            quantity: number | string;
            /** Format: int64 */
            version: number | string;
        };
        AdministratorDto: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            isActive: boolean;
            isBootstrapAdministrator: boolean;
            requiresPasswordChange: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        AdministratorSignInRequest: {
            username: string;
            password: string;
        };
        AvailableOrderAssigneeDto: {
            /** Format: uuid */
            employeeId: string;
            /** Format: uuid */
            organizationId: string;
            employeeDisplayName: string;
            organizationName: string;
        };
        BootstrapAdministratorRequest: {
            username: string;
            displayName: string;
            password: string;
        };
        ChangeOwnPasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ConfigureOrderPickingRequest: {
            pickingMode: components["schemas"]["PickingMode"];
            employeeIds: string[];
            /** Format: int64 */
            version: number | string;
        };
        CreateAdministratorRequest: {
            username: string;
            displayName: string;
        };
        CreatedAdministratorDto: {
            administrator: components["schemas"]["AdministratorDto"];
            temporaryPassword: string;
        };
        CreateEmployeeRequest: {
            code: string;
            displayName: string;
        };
        CreateOrderItemRequest: {
            /** Format: int32 */
            productId: number | string;
            /** Format: double */
            quantity: number | string;
        };
        CreateOrderRequest: {
            customerName: string;
            /** Format: date */
            dueDate: string;
            pickingMode: components["schemas"]["PickingMode"];
            employeeIds: string[];
            items?: null | components["schemas"]["CreateOrderItemRequest"][];
        };
        CreateOrganizationRequest: {
            code: string;
            name: string;
        };
        CreatePalletItemRequest: {
            /** Format: uuid */
            orderItemId: string;
            /** Format: double */
            quantity: number | string;
            /** Format: int64 */
            itemVersion: number | string;
        };
        CreatePalletRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: double */
            emptyPalletWeightKg: number | string;
            items: null | components["schemas"]["CreatePalletItemRequest"][];
        };
        CsrfTokenResponse: {
            token: string;
            headerName: string;
        };
        CurrentActor: {
            kind: components["schemas"]["ActorKind"];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: null | string;
            displayName: string;
            permissions: string[];
            /** Format: uuid */
            sessionId: string;
            /** @default false */
            requiresPasswordChange: boolean;
        };
        CurrentSessionResponse: {
            /** Format: date-time */
            expiresAtUtc: string;
            actor: components["schemas"]["CurrentActor"];
        };
        EmployeeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            code: string;
            displayName: string;
            isActive: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        EntityTagHeaderValue: {
            tag?: components["schemas"]["StringSegment"];
            isWeak?: boolean;
        };
        FileContentResult: {
            /** Format: byte */
            fileContents?: string;
            contentType?: null | string;
            fileDownloadName?: null | string;
            /** Format: date-time */
            lastModified?: null | string;
            entityTag?: null | components["schemas"]["EntityTagHeaderValue"];
            enableRangeProcessing?: boolean;
        };
        OrderAssigneeDto: {
            /** Format: uuid */
            employeeId: string;
            /** Format: uuid */
            organizationId: string;
            employeeDisplayName: string;
            /** Format: uuid */
            assignedById: string;
            assignedByName: string;
            /** Format: date-time */
            assignedAtUtc: string;
        };
        OrderDto: {
            /** Format: uuid */
            id: string;
            number: string;
            customerName: string;
            /** Format: date */
            dueDate: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: uuid */
            createdById: string;
            createdByName: string;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: uuid */
            updatedById: string;
            updatedByName: string;
            /** Format: date-time */
            updatedAtUtc: string;
            /** Format: date-time */
            publishedAtUtc: null | string;
            /** Format: int64 */
            version: number | string;
            pickingMode: components["schemas"]["PickingMode"];
            assignees: components["schemas"]["OrderAssigneeDto"][];
            items: components["schemas"]["OrderItemDto"][];
        };
        OrderItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            productId: number | string;
            productName: string;
            productSymbol: null | string;
            /** Format: double */
            quantity: number | string;
            unit: string;
            /** Format: double */
            unitWeightKg: null | number | string;
            status: components["schemas"]["OrderItemStatus"];
        };
        OrderItemStatus: number;
        OrderListItemDto: {
            /** Format: uuid */
            id: string;
            number: string;
            customerName: string;
            /** Format: date */
            dueDate: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: int32 */
            itemCount: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
            /** Format: int64 */
            version: number | string;
        };
        OrderStatus: number;
        OrganizationDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            isActive: boolean;
            /** Format: date-time */
            createdAtUtc: string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        PackPickingItemRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            itemVersion: number | string;
            /** Format: double */
            packedQuantity: number | string;
        };
        PagedResponseOfProductListItemResponse: {
            items: components["schemas"]["ProductListItemResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultOfOrderListItemDto: {
            items: components["schemas"]["OrderListItemDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultOfPalletListItemDto: {
            items: components["schemas"]["PalletListItemDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultOfPickingHistoryItemDto: {
            items: components["schemas"]["PickingHistoryItemDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultOfPickingOrderListItemDto: {
            items: components["schemas"]["PickingOrderListItemDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PalletCandidateItemDto: {
            /** Format: uuid */
            orderItemId: string;
            /** Format: int32 */
            productId: number | string;
            productName: string;
            productSymbol: null | string;
            /** Format: double */
            orderedQuantity: number | string;
            /** Format: double */
            packedQuantity: number | string;
            /** Format: double */
            palletizedQuantity: number | string;
            /** Format: double */
            availableForPalletQuantity: number | string;
            unit: string;
            /** Format: double */
            unitWeightKg: null | number | string;
            /** Format: int64 */
            version: number | string;
        };
        PalletCandidatesDto: {
            /** Format: uuid */
            orderId: string;
            orderNumber: string;
            customerName: string;
            /** Format: date */
            dueDate: string;
            items: components["schemas"]["PalletCandidateItemDto"][];
        };
        PalletDetailsDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            orderNumber: string;
            palletNumber: string;
            customerName: string;
            status: components["schemas"]["PalletStatus"];
            /** Format: double */
            emptyPalletWeightKg: number | string;
            /** Format: double */
            goodsWeightKg: number | string;
            /** Format: double */
            totalWeightKg: number | string;
            closedByKind: components["schemas"]["ActorKind"];
            /** Format: uuid */
            closedById: string;
            closedByName: string;
            /** Format: date-time */
            closedAtUtc: string;
            items: components["schemas"]["PalletDetailsItemDto"][];
            label: components["schemas"]["PalletLabelPreviewDto"];
            labelIssues: components["schemas"]["PalletLabelIssueDto"][];
        };
        PalletDetailsItemDto: {
            /** Format: uuid */
            orderItemId: string;
            /** Format: int32 */
            productId: number | string;
            productName: string;
            productSymbol: null | string;
            /** Format: double */
            quantity: number | string;
            unit: string;
            /** Format: double */
            unitWeightKg: number | string;
            /** Format: double */
            lineWeightKg: number | string;
        };
        PalletLabelItemDto: {
            productName: string;
            /** Format: double */
            quantity: number | string;
            unit: string;
        };
        PalletLabelIssueDto: {
            /** Format: int32 */
            number: number | string;
            mode: components["schemas"]["PalletLabelIssueMode"];
            actorKind: components["schemas"]["ActorKind"];
            actorDisplayName: string;
            /** Format: date-time */
            occurredAtUtc: string;
        };
        PalletLabelIssueMode: "Print" | "Download";
        PalletLabelLanguage: "Polish" | "English";
        PalletLabelIssueRequest: {
            mode: components["schemas"]["PalletLabelIssueMode"];
            language?: components["schemas"]["PalletLabelLanguage"];
        };
        PalletLabelPreviewDto: {
            orderNumber: string;
            palletNumber: string;
            customerName: string;
            /** Format: double */
            goodsWeightKg: number | string;
            /** Format: double */
            emptyPalletWeightKg: number | string;
            /** Format: double */
            totalWeightKg: number | string;
            items: components["schemas"]["PalletLabelItemDto"][];
        };
        PalletListItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            orderNumber: string;
            palletNumber: string;
            customerName: string;
            status: components["schemas"]["PalletStatus"];
            /** Format: double */
            goodsWeightKg: number | string;
            /** Format: double */
            emptyPalletWeightKg: number | string;
            /** Format: double */
            totalWeightKg: number | string;
            /** Format: int32 */
            itemCount: number | string;
            /** Format: date-time */
            closedAtUtc: string;
        };
        PalletStatus: number;
        PickingAction: number;
        PickingActorDto: {
            kind: components["schemas"]["ActorKind"];
            /** Format: uuid */
            id: string;
            displayName: string;
            /** Format: date-time */
            atUtc: string;
        };
        PickingHistoryItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            operationId: string;
            /** Format: uuid */
            orderItemId: string;
            productName: string;
            action: components["schemas"]["PickingAction"];
            fromStatus: components["schemas"]["OrderItemStatus"];
            toStatus: components["schemas"]["OrderItemStatus"];
            /** Format: double */
            packedQuantity: null | number | string;
            actorKind: components["schemas"]["ActorKind"];
            /** Format: uuid */
            actorId: string;
            actorDisplayName: string;
            /** Format: date-time */
            occurredAtUtc: string;
        };
        PickingItemActionsDto: {
            canReserve: boolean;
            canRelease: boolean;
            canPack: boolean;
            canUndoPack: boolean;
        };
        PickingItemDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            productId: number | string;
            productName: string;
            productSymbol: null | string;
            /** Format: double */
            orderedQuantity: number | string;
            /** Format: double */
            remainingQuantity: number | string;
            unit: string;
            status: components["schemas"]["OrderItemStatus"];
            /** Format: int64 */
            version: number | string;
            reservedBy: null | components["schemas"]["PickingActorDto"];
            /** Format: double */
            packedQuantity: null | number | string;
            packedBy: null | components["schemas"]["PickingActorDto"];
            /** Format: double */
            palletizedQuantity: number | string;
            /** Format: double */
            availableForPalletQuantity: number | string;
            palletAssignments: components["schemas"]["PickingPalletAssignmentDto"][];
            actions: components["schemas"]["PickingItemActionsDto"];
        };
        PickingMode: number;
        PickingMutationRequest: {
            /** Format: uuid */
            operationId: string;
            /** Format: int64 */
            itemVersion: number | string;
        };
        PickingOrderDetailsDto: {
            /** Format: uuid */
            id: string;
            number: string;
            customerName: string;
            /** Format: date */
            dueDate: string;
            pickingMode: components["schemas"]["PickingMode"];
            pickingStatus: components["schemas"]["PickingOrderStatus"];
            /** Format: int32 */
            totalItemCount: number | string;
            /** Format: int32 */
            completedItemCount: number | string;
            /** Format: int32 */
            progressPercent: number | string;
            isAssignedToCurrentUser: boolean;
            canExecutePicking: boolean;
            canCreatePallet: boolean;
            items: components["schemas"]["PickingItemDto"][];
        };
        PickingOrderListItemDto: {
            /** Format: uuid */
            id: string;
            number: string;
            customerName: string;
            /** Format: date */
            dueDate: string;
            pickingMode: components["schemas"]["PickingMode"];
            pickingStatus: components["schemas"]["PickingOrderStatus"];
            /** Format: int32 */
            totalItemCount: number | string;
            /** Format: int32 */
            completedItemCount: number | string;
            /** Format: int32 */
            progressPercent: number | string;
            isAssignedToCurrentUser: boolean;
        };
        PickingOrderStatus: number;
        PickingPalletAssignmentDto: {
            /** Format: uuid */
            palletId: string;
            palletNumber: string;
            /** Format: double */
            quantity: number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ProductDetailsResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            description: null | string;
            unit: null | string;
            /** Format: double */
            unitWeightKg: null | number | string;
            primaryBarcode: null | string;
            additionalBarcodes: string[];
            vat: null | components["schemas"]["ProductVatDto"];
            imageUrl: null | string;
            warehouses: components["schemas"]["ProductStockDto"][];
            prices: components["schemas"]["ProductPriceDto"][];
        };
        ProductListItemResponse: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            unit: null | string;
            /** Format: double */
            unitWeightKg: null | number | string;
            imageUrl: null | string;
            stock: null | components["schemas"]["ProductStockDto"];
        };
        ProductPriceDto: {
            /** Format: int32 */
            level: number | string;
            name: string;
            /** Format: double */
            net: null | number | string;
            /** Format: double */
            gross: null | number | string;
            currency: null | string;
        };
        ProductStockDto: {
            /** Format: int32 */
            warehouseId: number | string;
            warehouseSymbol: null | string;
            warehouseName: null | string;
            isMain: boolean;
            /** Format: double */
            quantity: number | string;
            /** Format: double */
            reserved: number | string;
            /** Format: double */
            available: number | string;
            /** Format: double */
            minimum: null | number | string;
            /** Format: double */
            maximum: null | number | string;
            unit: null | string;
        };
        ProductVatDto: {
            /** Format: int32 */
            id: number | string;
            name: null | string;
            symbol: null | string;
            /** Format: double */
            rate: null | number | string;
        };
        PublicEmployeeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            code: string;
            displayName: string;
        };
        PublicOrganizationDto: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        ResetAdministratorPasswordRequest: {
            password: string;
        };
        SelectEmployeeRequest: {
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            employeeId: string;
        };
        SetActiveRequest: {
            isActive: boolean;
        };
        StringSegment: {
            buffer?: null | string;
            /** Format: int32 */
            offset?: number | string;
            /** Format: int32 */
            length?: number | string;
            value?: null | string;
            hasValue?: boolean;
        };
        UpdateAdministratorRequest: {
            username: string;
            displayName: string;
        };
        UpdateEmployeeRequest: {
            code: string;
            displayName: string;
        };
        UpdateOrderRequest: {
            customerName: string;
            /** Format: date */
            dueDate: string;
            /** Format: int64 */
            version: number | string;
        };
        UpdateOrganizationRequest: {
            code: string;
            name: string;
        };
        ValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        VersionRequest: {
            /** Format: int64 */
            version: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
