import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FormEvent, useState } from 'react'
import { useI18n } from '../../../app/i18n/i18nContext'
import { apiClient } from '../../../api/client'
import { getCsrfHeader } from '../../../api/csrf'
import { ApiRequestError } from '../../../api/apiError'

type PackagingType = { id: string; code: string; name: string; tareWeightKg: number; defaultCapacity: number | null; isActive: boolean; version: number }
type Page = { items: PackagingType[] }
const client = apiClient as any

export function PackagingTypesPage() {
  const { t } = useI18n(); const queryClient = useQueryClient(); const [error, setError] = useState<string | null>(null)
  const query = useQuery<Page>({ queryKey: ['packaging-types'], queryFn: async () => { const { data, response } = await client.GET('/api/packaging-types', { params: { query: { page: 1, pageSize: 100 } } }); if (!response.ok) throw new Error(); return data } })
  const create = useMutation({ mutationFn: async (form: HTMLFormElement) => { const d = new FormData(form); const headers = await getCsrfHeader(); const { error: apiError, response } = await client.POST('/api/packaging-types', { body: { code: String(d.get('code')), name: String(d.get('name')), tareWeightKg: Number(d.get('tareWeightKg')), defaultCapacity: d.get('defaultCapacity') ? Number(d.get('defaultCapacity')) : null, isActive: true }, headers }); if (!response.ok) throw new ApiRequestError(response.status, problemDetail(apiError)) }, onSuccess: () => { setError(null); void queryClient.invalidateQueries({ queryKey: ['packaging-types'] }) }, onError: (reason) => setError(reason instanceof Error ? reason.message : t('packaging.error')) })
  const toggle = useMutation({ mutationFn: async (item: PackagingType) => { const headers = await getCsrfHeader(); const { response } = await client.PUT('/api/packaging-types/{id}/active', { params: { path: { id: item.id } }, body: { isActive: !item.isActive, version: item.version }, headers }); if (!response.ok) throw new Error() }, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ['packaging-types'] }), onError: () => setError(t('packaging.error')) })
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); create.mutate(event.currentTarget) }
  return <section className="mx-auto max-w-5xl"><div className="mb-6"><h2 className="text-2xl font-bold">{t('packaging.title')}</h2><p className="mt-1 text-sm text-slate-600">{t('packaging.description')}</p></div><form className="grid gap-3 rounded-xl border border-slate-300 bg-white p-5 sm:grid-cols-4" onSubmit={submit}><input className="h-12 rounded-lg border border-slate-300 px-3" name="code" placeholder={t('packaging.code')} required /><input className="h-12 rounded-lg border border-slate-300 px-3" name="name" placeholder={t('packaging.name')} required /><input className="h-12 rounded-lg border border-slate-300 px-3" min="0" name="tareWeightKg" placeholder={t('packaging.tare')} required step="0.0001" type="number" /><input className="h-12 rounded-lg border border-slate-300 px-3" min="0.0001" name="defaultCapacity" placeholder={t('packaging.capacity')} step="0.0001" type="number" /><button className="min-h-12 rounded-lg bg-blue-950 px-4 font-semibold text-white sm:col-span-4" disabled={create.isPending} type="submit">{t('packaging.add')}</button></form>{error && <p className="mt-4 rounded border border-red-300 bg-red-50 p-3 text-red-800" role="alert">{error}</p>}{query.isLoading ? <p className="mt-6">{t('packaging.loading')}</p> : <div className="mt-6 overflow-hidden rounded-xl border border-slate-300 bg-white"><table className="w-full text-left"><thead className="bg-slate-100 text-sm text-slate-600"><tr><th className="p-3">{t('packaging.code')}</th><th className="p-3">{t('packaging.name')}</th><th className="p-3">{t('packaging.tare')}</th><th className="p-3">{t('packaging.status')}</th><th className="p-3" /></tr></thead><tbody>{query.data?.items.map(x => <tr className="border-t border-slate-200" key={x.id}><td className="p-3 font-mono">{x.code}</td><td className="p-3">{x.name}</td><td className="p-3">{x.tareWeightKg} kg</td><td className="p-3">{x.isActive ? t('packaging.active') : t('packaging.inactive')}</td><td className="p-3 text-right"><button className="admin-action-button" disabled={toggle.isPending} onClick={() => toggle.mutate(x)} type="button">{x.isActive ? t('packaging.deactivate') : t('packaging.activate')}</button></td></tr>)}</tbody></table></div>}</section>
}

function problemDetail(error: unknown): string | undefined { return typeof error === 'object' && error !== null && 'detail' in error && typeof error.detail === 'string' ? error.detail : undefined }
