using Microsoft.EntityFrameworkCore;
using Npgsql;
using SubiektMobile.Application.Customers;
using SubiektMobile.Application.Products;
using SubiektMobile.Domain.Customers;
using SubiektMobile.Domain.Identity;
using SubiektMobile.Infrastructure.Persistence.Application;

namespace SubiektMobile.Infrastructure.Customers;

public sealed class PackagingStore(ApplicationDbContext db) : IPackagingStore
{
    public async Task<PagedResult<PackagingTypeDto>> ListPackagingTypesAsync(string? search, bool? active, int page, int pageSize, CancellationToken ct)
    { var q = db.PackagingTypes.AsNoTracking(); if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToUpper(); q = q.Where(x => x.NormalizedCode.Contains(s) || x.Name.ToUpper().Contains(s)); } if (active is not null) q = q.Where(x => x.IsActive == active); var total = await q.CountAsync(ct); var items = await q.OrderBy(x => x.Code).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new PackagingTypeDto(x.Id, x.Code, x.Name, x.TareWeightKg, x.DefaultCapacity, x.IsActive, x.UpdatedAtUtc, x.Version)).ToListAsync(ct); return Page(items, page, pageSize, total); }
    public Task<PackagingType?> FindPackagingTypeAsync(Guid id, bool tracking, CancellationToken ct) => (tracking ? db.PackagingTypes : db.PackagingTypes.AsNoTracking()).SingleOrDefaultAsync(x => x.Id == id, ct);
    public async Task<PackagingStoreResult> AddPackagingTypeAsync(PackagingType e, AuditEntry a, CancellationToken ct) { db.PackagingTypes.Add(e); db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<PackagingStoreResult> SavePackagingTypeAsync(PackagingType e, long v, AuditEntry a, CancellationToken ct) { db.Entry(e).Property(x => x.Version).OriginalValue = v; db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<PagedResult<CustomerPackagingCodeDto>> ListPackagingCodesAsync(Guid customer, Guid? site, int page, int pageSize, CancellationToken ct)
    { var q = from x in db.CustomerPackagingCodes.AsNoTracking().Where(x => x.CustomerId == customer && x.CustomerSiteId == site) join p in db.PackagingTypes.AsNoTracking() on x.PackagingTypeId equals p.Id orderby x.Code select new CustomerPackagingCodeDto(x.Id, x.CustomerId, x.CustomerSiteId, x.PackagingTypeId, p.Code, p.Name, x.Code, x.IsActive, x.Version); var total = await q.CountAsync(ct); return Page(await q.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync(ct), page, pageSize, total); }
    public Task<CustomerPackagingCode?> FindPackagingCodeAsync(Guid customer, Guid? site, Guid id, bool tracking, CancellationToken ct) => (tracking ? db.CustomerPackagingCodes : db.CustomerPackagingCodes.AsNoTracking()).SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == site && x.Id == id, ct);
    public async Task<PackagingStoreResult> AddPackagingCodeAsync(CustomerPackagingCode e, AuditEntry a, CancellationToken ct) { db.CustomerPackagingCodes.Add(e); db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<PackagingStoreResult> SavePackagingCodeAsync(CustomerPackagingCode e, long v, AuditEntry a, CancellationToken ct) { db.Entry(e).Property(x => x.Version).OriginalValue = v; db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<PagedResult<CustomerPartMappingDto>> ListPartMappingsAsync(Guid customer, Guid? site, string? search, int page, int pageSize, CancellationToken ct)
    { var q = db.CustomerPartMappings.AsNoTracking().Where(x => x.CustomerId == customer && x.CustomerSiteId == site); if (!string.IsNullOrWhiteSpace(search)) { var s = search.Trim().ToUpper(); q = q.Where(x => x.NormalizedCustomerPartNumber.Contains(s)); } var total = await q.CountAsync(ct); var items = await q.OrderBy(x => x.CustomerPartNumber).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new CustomerPartMappingDto(x.Id, x.CustomerId, x.CustomerSiteId, x.CustomerPartNumber, x.ProductId, null, null, x.DefaultPackagingTypeId, x.EngineeringChange, x.IsActive, x.Version)).ToListAsync(ct); return Page(items, page, pageSize, total); }
    public Task<CustomerPartMapping?> FindPartMappingAsync(Guid customer, Guid? site, Guid id, bool tracking, CancellationToken ct) => (tracking ? db.CustomerPartMappings : db.CustomerPartMappings.AsNoTracking()).SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == site && x.Id == id, ct);
    public async Task<PackagingStoreResult> AddPartMappingAsync(CustomerPartMapping e, AuditEntry a, CancellationToken ct) { db.CustomerPartMappings.Add(e); db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<PackagingStoreResult> SavePartMappingAsync(CustomerPartMapping e, long v, AuditEntry a, CancellationToken ct) { db.Entry(e).Property(x => x.Version).OriginalValue = v; db.AuditEntries.Add(a); return await Save(ct); }
    public async Task<CustomerPartResolutionDto> ResolveAsync(Guid customer, Guid? site, string part, CancellationToken ct)
    { var normalized = part.Trim().ToUpperInvariant(); var mapping = site is null ? null : await db.CustomerPartMappings.AsNoTracking().SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == site && x.NormalizedCustomerPartNumber == normalized && x.IsActive, ct); mapping ??= await db.CustomerPartMappings.AsNoTracking().SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == null && x.NormalizedCustomerPartNumber == normalized && x.IsActive, ct); if (mapping is null) return new CustomerPartResolutionDto(part.Trim(), CustomerPartReadiness.MissingMapping, null, null); var dto = new CustomerPartMappingDto(mapping.Id, mapping.CustomerId, mapping.CustomerSiteId, mapping.CustomerPartNumber, mapping.ProductId, null, null, mapping.DefaultPackagingTypeId, mapping.EngineeringChange, mapping.IsActive, mapping.Version); if (mapping.DefaultPackagingTypeId is null) return new CustomerPartResolutionDto(mapping.CustomerPartNumber, CustomerPartReadiness.Mapped, dto, null); var type = await db.PackagingTypes.AsNoTracking().SingleOrDefaultAsync(x => x.Id == mapping.DefaultPackagingTypeId && x.IsActive, ct); if (type is null) return new CustomerPartResolutionDto(mapping.CustomerPartNumber, CustomerPartReadiness.PackagingUnavailable, dto, null); var code = site is null ? null : await db.CustomerPackagingCodes.AsNoTracking().SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == site && x.PackagingTypeId == type.Id && x.IsActive, ct); code ??= await db.CustomerPackagingCodes.AsNoTracking().SingleOrDefaultAsync(x => x.CustomerId == customer && x.CustomerSiteId == null && x.PackagingTypeId == type.Id && x.IsActive, ct); var codeDto = code is null ? null : new CustomerPackagingCodeDto(code.Id, code.CustomerId, code.CustomerSiteId, type.Id, type.Code, type.Name, code.Code, code.IsActive, code.Version); return new CustomerPartResolutionDto(mapping.CustomerPartNumber, CustomerPartReadiness.Mapped, dto, codeDto); }
    private async Task<PackagingStoreResult> Save(CancellationToken ct) { try { await db.SaveChangesAsync(ct); return PackagingStoreResult.Success; } catch (DbUpdateConcurrencyException) { return PackagingStoreResult.Conflict; } catch (DbUpdateException ex) when (Postgres(ex)?.SqlState == PostgresErrorCodes.UniqueViolation) { return PackagingStoreResult.Conflict; } }
    private static PostgresException? Postgres(Exception e) { for (var x = e; x is not null; x = x.InnerException!) { if (x is PostgresException p) return p; if (x.InnerException is null) break; } return null; }
    private static PagedResult<T> Page<T>(IReadOnlyList<T> items, int page, int size, int total) => new(items, page, size, total, total == 0 ? 0 : (int)Math.Ceiling(total / (double)size));
}
