using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SubiektMobile.Domain.Customers;

namespace SubiektMobile.Infrastructure.Persistence.Application.Configurations;

public sealed class PackagingTypeConfiguration : IEntityTypeConfiguration<PackagingType>
{ public void Configure(EntityTypeBuilder<PackagingType> b) { b.ToTable("packaging_types"); b.HasKey(x => x.Id); b.Property(x => x.Code).HasMaxLength(64).IsRequired(); b.Property(x => x.NormalizedCode).HasMaxLength(64).IsRequired(); b.Property(x => x.Name).HasMaxLength(120).IsRequired(); b.Property(x => x.TareWeightKg).HasPrecision(18, 4); b.Property(x => x.DefaultCapacity).HasPrecision(18, 4); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => x.NormalizedCode).IsUnique(); b.HasIndex(x => new { x.IsActive, x.UpdatedAtUtc }); } }
public sealed class CustomerPackagingCodeConfiguration : IEntityTypeConfiguration<CustomerPackagingCode>
{ public void Configure(EntityTypeBuilder<CustomerPackagingCode> b) { b.ToTable("customer_packaging_codes"); b.HasKey(x => x.Id); b.Property(x => x.Code).HasMaxLength(64).IsRequired(); b.Property(x => x.NormalizedCode).HasMaxLength(64).IsRequired(); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => new { x.CustomerId, x.PackagingTypeId }).HasFilter("\"CustomerSiteId\" IS NULL").IsUnique(); b.HasIndex(x => new { x.CustomerSiteId, x.PackagingTypeId }).HasFilter("\"CustomerSiteId\" IS NOT NULL").IsUnique(); b.HasIndex(x => new { x.CustomerId, x.NormalizedCode }).HasFilter("\"CustomerSiteId\" IS NULL").IsUnique(); b.HasIndex(x => new { x.CustomerSiteId, x.NormalizedCode }).HasFilter("\"CustomerSiteId\" IS NOT NULL").IsUnique(); b.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CustomerSite>().WithMany().HasForeignKey(x => x.CustomerSiteId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PackagingType>().WithMany().HasForeignKey(x => x.PackagingTypeId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class CustomerPartMappingConfiguration : IEntityTypeConfiguration<CustomerPartMapping>
{ public void Configure(EntityTypeBuilder<CustomerPartMapping> b) { b.ToTable("customer_part_mappings"); b.HasKey(x => x.Id); b.Property(x => x.CustomerPartNumber).HasMaxLength(80).IsRequired(); b.Property(x => x.NormalizedCustomerPartNumber).HasMaxLength(80).IsRequired(); b.Property(x => x.EngineeringChange).HasMaxLength(80); b.Property(x => x.Version).IsConcurrencyToken(); b.HasIndex(x => new { x.CustomerId, x.NormalizedCustomerPartNumber }).HasFilter("\"CustomerSiteId\" IS NULL").IsUnique(); b.HasIndex(x => new { x.CustomerSiteId, x.NormalizedCustomerPartNumber }).HasFilter("\"CustomerSiteId\" IS NOT NULL").IsUnique(); b.HasIndex(x => new { x.CustomerId, x.CustomerSiteId, x.IsActive }); b.HasOne<Customer>().WithMany().HasForeignKey(x => x.CustomerId).OnDelete(DeleteBehavior.Restrict); b.HasOne<CustomerSite>().WithMany().HasForeignKey(x => x.CustomerSiteId).OnDelete(DeleteBehavior.Restrict); b.HasOne<PackagingType>().WithMany().HasForeignKey(x => x.DefaultPackagingTypeId).OnDelete(DeleteBehavior.Restrict); } }
